### ISSUE TITLE
It is zig 0.14.0-dev.2456+a68119f8f compatible?

### ISSUE THREAD

**Issue by Tidy-Coder** [david-vanderson/dvui#169]
Hello. When I compile the example code with raylib-ontop, the following error is produced on my terminal:
`raylib-ontop
└─ run raylib-ontop
   └─ zig build-exe raylib-ontop Debug native 2 errors
src/Backend.zig:128:30: error: no field named 'Struct' in union 'builtin.Type'
    inline for (@typeInfo(I).Struct.decls) |decl| {
                             ^~~~~~
/home/tidycoder/programs/zig/zig/lib/std/builtin.zig:557:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
src/Font.zig:134:37: error: no field named 'Struct' in union 'builtin.Type'
    inline for (@typeInfo(TTFBytes).Struct.decls) |decl| {
                                    ^~~~~~
/home/tidycoder/programs/zig/zig/lib/std/builtin.zig:557:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
referenced by:
    init: src/dvui.zig:2655:64
    main: examples/raylib-ontop.zig:34:35
    4 reference(s) hidden; use '-freference-trace=6' to see all references`
I don't know if this compilation error result from my zig version, for information, I use linux.

**Comment by Tidy-Coder** [comment]
I have the following error when I execute the  zig build -fsys=sdl2 sdl-standalone command:
`sdl-standalone
└─ run sdl-standalone
   └─ zig build-exe sdl-standalone Debug native 1 errors
src/backends/sdl_backend.zig:21:47: error: no field named 'Enum' in union 'builtin.Type'
cursor_backing: [@typeInfo(dvui.enums.Cursor).Enum.fields.len]?*c.SDL_Cursor = [_]?*c.SDL_Cursor{null} ** @typeInfo(dvui.enums.Cursor).Enum.fields.len,
                                              ^~~~
/home/tidycoder/programs/zig/zig/lib/std/builtin.zig:557:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
`

**Comment by david-vanderson** [comment]
That sounds like the same 0.14 problem - can you confirm you are trying with zig 0.13?

**Comment by Tidy-Coder** [comment]
Ah, sorry, now it work with zig 0.13 perfectly. thanks for this repo, the community is very reactive, and the goals are goods: Creating the perfect gui framework for the robustness and optimal programming language: zig.

**Comment by david-vanderson** [comment]
Thanks!
