### ISSUE TITLE
raylib on macos zig 0.14

### ISSUE THREAD

**Issue by david-vanderson** [david-vanderson/dvui#176]
It looks like raylib has an xcode-specific dependency that doesn't quite work with zig 0.14, so I've disabled raylib on macos for now.

```
/Users/dvanderson/.cache/zig/p/12208da4dfcd9b53fb367375fb612ec73f38e53015f1ce6ae6d6e8437a637078e170/build.zig:13:14: error: expected type '*Build.Module', found '**Build.Module'
    addPaths(&lib.root_module); // just for testing
             ^~~~~~~~~~~~~~~~
/Users/dvanderson/.cache/zig/p/12208da4dfcd9b53fb367375fb612ec73f38e53015f1ce6ae6d6e8437a637078e170/build.zig:13:14: note: pointer type child '*Build.Module' cannot cast into pointer type child 'Build.Module'
/Users/dvanderson/apps/zig-macos-aarch64-0.14.0-dev.2851+b074fb7dd/lib/std/Build/Module.zig:1:1: note: struct declared here
/// The one responsible for creating this module.
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dvanderson/.cache/zig/p/12208da4dfcd9b53fb367375fb612ec73f38e53015f1ce6ae6d6e8437a637078e170/build.zig:19:22: note: parameter type declared here
pub fn addPaths(mod: *std.Build.Module) void {
                     ^~~~~~~~~~~~~~~~~
referenced by:
    runBuild__anon_69983: /Users/dvanderson/apps/zig-macos-aarch64-0.14.0-dev.2851+b074fb7dd/lib/std/Build.zig:2388:33
    dependencyInner__anon_59142: /Users/dvanderson/apps/zig-macos-aarch64-0.14.0-dev.2851+b074fb7dd/lib/std/Build.zig:2369:29
    9 reference(s) hidden; use '-freference-trace=11' to see all references
```

**Comment by david-vanderson** [comment]
This is working now, so I've re-enabled raylib on macos by default.
